# Generated by Django 6.1 on 2026-09-29 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0020_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='family_guardian',
            field=models.ForeignKey(blank=True, help_text='Set for a parent-level payment allocated across children.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_payments', to='smsApp.guardian'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='smsApp.invoice'),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='smsApp.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='smsApp.payment')),
            ],
            options={
                'db_table': 'payment_allocations',
                'constraints': [models.UniqueConstraint(fields=('payment', 'invoice'), name='uniq_payment_invoice_allocation'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_allocation_amount_positive')],
            },
        ),
    ]
