# Generated by Django 6.1 on 2026-10-01 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0021_payment_family_guardian_alter_payment_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='#6f1d32', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a six-digit hex color.')]),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_color',
            field=models.CharField(default='#4d4d4d', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a six-digit hex color.')]),
        ),
        migrations.AddField(
            model_name='school',
            name='subdomain',
            field=models.CharField(blank=True, help_text='Unique lowercase school portal identifier.', max_length=63, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Use 1-63 lowercase letters, numbers, or internal hyphens.', regex='^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$')]),
        ),
    ]
