# Generated by Django 6.1 on 2026-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0022_school_primary_color_school_secondary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short_name',
            field=models.CharField(blank=True, help_text='Compact name used in dashboard navigation, e.g. Mihango-High.', max_length=80),
        ),
    ]
