# Generated by Django 6.1 on 2026-10-01 11:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0023_school_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='class_groups',
            field=models.ManyToManyField(blank=True, related_name='grouped_fee_structures', to='smsApp.class'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='paybill_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='feestructureitem',
            name='particulars',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='feestructureitem',
            name='term_1_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructureitem',
            name='term_2_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructureitem',
            name='term_3_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='takes_coding_robotics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_option',
            field=models.CharField(blank=True, choices=[('NONE', 'No transport'), ('ONE_WAY', 'One way'), ('TWO_WAY', 'Two way')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_period',
            field=models.CharField(blank=True, choices=[('NONE', 'Not applicable'), ('MORNING', 'Morning'), ('EVENING', 'Evening'), ('BOTH', 'Morning and evening')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_route',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='FeeStructureTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=150)),
                ('one_way_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('two_way_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_options', to='smsApp.feestructure')),
            ],
            options={
                'db_table': 'fee_structure_transport',
                'ordering': ['route_name'],
            },
        ),
    ]
