# Generated by Django 6.1 on 2026-10-01 17:08

import django.db.models.deletion
from django.db import migrations, models


def unlink_inactive_modules(apps, schema_editor):
    Class = apps.get_model("smsApp", "Class")
    Department = apps.get_model("smsApp", "Department")
    Class.objects.update(program=None, campus=None)
    Department.objects.update(campus=None)


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0024_feestructure_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='smsApp.program'),
        ),
        migrations.RunPython(unlink_inactive_modules, migrations.RunPython.noop),
    ]
