# Generated by Django 6.1 on 2026-10-02 16:07

from django.db import migrations, models


def mark_optional_items(apps, schema_editor):
    FeeStructureItem = apps.get_model("smsApp", "FeeStructureItem")
    for item in FeeStructureItem.objects.select_related("category").iterator():
        label = f"{item.particulars} {item.category.name}".casefold()
        if "robot" in label or "coding" in label:
            FeeStructureItem.objects.filter(pk=item.pk).update(section="OPTIONAL", is_mandatory=False)


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0028_principal_manager_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructureitem',
            name='section',
            field=models.CharField(choices=[('TUITION', 'Tuition'), ('OPTIONAL', 'Optional subjects')], db_index=True, default='TUITION', max_length=10),
        ),
        migrations.RunPython(mark_optional_items, migrations.RunPython.noop),
    ]
