# Generated by Django 6.1 on 2026-10-03 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_manager_roles(apps, schema_editor):
    User = apps.get_model("smsApp", "User")
    User.objects.filter(role="PRINCIPAL_DIRECTOR").update(role="MANAGER")


def restore_previous_roles(apps, schema_editor):
    User = apps.get_model("smsApp", "User")
    User.objects.filter(role="MANAGER").update(role="PRINCIPAL_DIRECTOR")
    User.objects.filter(role="PRINCIPAL").update(role="ACADEMIC_ADMIN")


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0030_performance_indexes'),
    ]

    operations = [
        migrations.RunPython(migrate_manager_roles, restore_previous_roles),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['STAFF_ADMIN', 'ACADEMIC_ADMIN', 'FINANCE_ADMIN', 'MANAGER', 'PRINCIPAL', 'TEACHER', 'EXAM_OFFICER', 'CLASS_TEACHER', 'DEPARTMENT_HEAD', 'ACCOUNTANT', 'LIBRARIAN']}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MANAGER', 'Manager'), ('PRINCIPAL', 'Principal'), ('DEPUTY_PRINCIPAL', 'Deputy Principal'), ('STAFF_ADMIN', 'Staff Admin'), ('ACADEMIC_ADMIN', 'Academic Admin'), ('FINANCE_ADMIN', 'Finance Admin'), ('TEACHER', 'Teacher/Lecturer'), ('EXAM_OFFICER', 'Examination Officer'), ('CLASS_TEACHER', 'Class Teacher'), ('DEPARTMENT_HEAD', 'Department Head'), ('ACCOUNTANT', 'Accountant/Finance Officer'), ('LIBRARIAN', 'Librarian'), ('STUDENT', 'Student'), ('PARENT', 'Parent/Guardian')], db_index=True, default='STUDENT', help_text='Coarse role for UI/dashboard routing. Authorization decisions must still check Django permissions.', max_length=20),
        ),
    ]
