# Generated by Django 6.1 on 2026-10-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0031_alter_staff_user_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text="Require a new password at the user's next browser sign-in."),
        ),
    ]
